defaultProject: hub-interndev-env-20250516
defaultLocation: US
defaultDataset: dataform
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0
vars:
    table: "agency"
    EXTERNAL_DATASET: hub_dna_ext_dev
    RAW_DATASET: hub_dna_bronze_dev
    SILVER_DATASET: hub_dna_silver_dev
    gcs_uri: "gs://hud-dna-datalake/epic_ca/Agency/2025/03-20/2025-03-20 00:05:14Z162"
    raw_suffix : "raw_"