config {
    type: "table",
    tags: ["ext_activity_js"],
    name : dataform.projectConfig.vars.table,
    schema: dataform.projectConfig.vars.RAW_DATASET
}

pre_operations {
    ${functions.external_table(
      dataform.projectConfig.vars.table,
      dataform.projectConfig.vars.EXTERNAL_DATASET,
      dataform.projectConfig.vars.gcs_uri
    )}
}

select *
from ${dataform.projectConfig.vars.EXTERNAL_DATASET}.${dataform.projectConfig.vars.table}



